apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: satisfactory
  namespace: games
spec:
  interval: 5m
  chart:
    spec:
      chart: satisfactory
      version: 1.0.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 1m
      valuesFiles:
        - values.yaml
  values:
    hostNetwork: true
    env:
      AUTOPAUSE: false
      MAXPLAYERS: 8
      PGID: 1000
      PUID: 1000
      STEAMBETA: true
    persistence:
      config:
        enabled: true
        size: 5Gi
        mountPath: /config
