apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plex
  namespace: plex
spec:
  interval: 6m
  chart:
    spec:
      chart: plex
      version: 6.3.3
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 1m
      valuesFiles:
        - values.yaml
  values:
    image:
      repository: ghcr.io/k8s-at-home/plex-pass
      tag: latest
    ingress:
      # -- Enable and configure ingress settings for the chart under this key.
      # @default -- See values.yaml
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx"
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
        hosts:
        - host: plex.crystalnet.org
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - plex.crystalnet.org
          secretName: plex.crystalnet.org
    env:
      # -- Set the container timezone
      TZ: UTC
      # ADVERTISE_IP:
      # ALLOWED_NETWORKS:
      PLEX_CLAIM: "claim-saNWymUEhMHm2bVxxeif"
      PLEX_PREFERENCE_1: "FriendlyName=deathstar 2.0"
    persistence:
      config:
        enabled: true
        retain: true
        accessMode: ReadWriteOnce
      movies-1080p:
        enabled: true
        mountPath: /data-movies-1080p
        existingClaim: movies-1080p
      movies-2160p:
        enabled: true
        mountPath: /data-movies-2160p
        existingClaim: movies-2160p
      serien:
        enabled: true
        mountPath: /data-serien
        existingClaim: serien
      anime:
        enabled: true
        mountPath: /data-anime
        existingClaim: anime
      animemovies:
        enabled: true
        mountPath: /data-animemovies
        existingClaim: animemovies
      festivals:
        enabled: true
        mountPath: /data-festivals
        existingClaim: festivals
      dmax:
        enabled: true
        mountPath: /data-dmax
        existingClaim: dmax
      transcode:
        enabled: true
        mountPath: /transcode
        accessMode: ReadWriteMany
        size: 20Gi
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      supplementalGroups:
      - 44
      - 109
    resources:
      requests:
        gpu.intel.com/i915: 1
        cpu: 200m
        memory: 256Mi
      limits:
        gpu.intel.com/i915: 1
        cpu: 4
        memory: 16Gi
