apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tautulli
  namespace: plex
spec:
  interval: 6m
  chart:
    spec:
      chart: tautulli
      version: 11.3.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 1m
      valuesFiles:
        - values.yaml
  values:
    ingress:
      # -- Enable and configure ingress settings for the chart under this key.
      # @default -- See values.yaml
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx"
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
        hosts:
        - host: tautulli.crystalnet.org
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - tautulli.crystalnet.org
          secretName: tautulli.crystalnet.org
    persistence:
      config:
        enabled: true
        accessMode: ReadWriteOnce
        size: 1Gi
