apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: librespeed
  namespace: crystalnet
spec:
  interval: 6m
  chart:
    spec:
      chart: librespeed
      version: 5.3.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 1m
      valuesFiles:
        - values.yaml
  values:
    ingress:
      # -- Enable and configure ingress settings for the chart under this key.
      # @default -- See values.yaml
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx"
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
          nginx.ingress.kubernetes.io/proxy-body-size: 21M
        hosts:
        - host: speedtest.crystalnet.org
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - speedtest.crystalnet.org
          secretName: speedtest.crystalnet.org
