apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: privatebin
  namespace: crystalnet
spec:
  interval: 1m
  chart:
    spec:
      chart: privatebin
      version: 1.2.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 1m
      valuesFiles:
        - values.yaml
  values:
    ingress:
      # -- Enable and configure ingress settings for the chart under this key.
      # @default -- See values.yaml
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx"
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
        hosts:
        - host: paste.crystalnet.org
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - paste.crystalnet.org
          secretName: paste.crystalnet.org
    postgresql:
      enabled: true
      persistence:
        accessMode: ReadWriteOnce
        enabled: true
    config:
      main:
        name: "CrystalPaste"
    persistence:
      data:
        enabled: false
        accessMode: ReadWriteOnce
        mountPath: /srv/data
