apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: searx
  namespace: crystalnet
spec:
  interval: 6m
  chart:
    spec:
      chart: searx
      version: 5.5.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 1m
      valuesFiles:
        - values.yaml
  values:
    image:
      # -- image repository
      repository: searx/searx
      # -- image tag
      tag: latest
    searx:
      existingSecret:
      baseUrl: "https://search.crystalnet.org"
      mortyKey: "Uk6YFd4FXj9yymoOo1hE6rsp7v/pSxsA"
    ingress:
      # -- Enable and configure ingress settings for the chart under this key.
      # @default -- See values.yaml
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx"
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
        hosts:
        - host: search.crystalnet.org
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - search.crystalnet.org
          secretName: search.crystalnet.org

